name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - name: Fetch Itch.io games
        run: node scripts/fetch-itch-games.js
        env:
          ITCH_API_KEY: ${{ secrets.ITCH_API_KEY }}
      - run: pnpm build
        env:
          NEXT_PUBLIC_GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
